#include "base/base_os.c"
#include "base/base_arena.c"
#include "base/base_string.c"
#include "base/base_math.c"
#include "base/base_random.c"

#include "glad/glad.c"

#include "render/render.c"
#include "draw/draw.c"
#include "phys/physics.c"
#include "input.c"
#include "event.c"
#include "entity.c"
#include "game.c"
#include "global.c"
#include "main.c"
